# Generated by Django 6.0.1 on 2026-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
