# Generated by Django 6.0.1 on 2026-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_alter_perfil_telefono_alter_publicacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler'), ('CAMBIO', 'Cambio / Permuta')], max_length=10, null=True),
        ),
    ]
