# Generated by Django 6.0.1 on 2026-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0005_perfil_correo_perfil_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='prefijo',
            field=models.CharField(choices=[('503', 'SV +503'), ('502', 'GT +502'), ('504', 'HN +504'), ('505', 'NI +505'), ('506', 'CR +506'), ('1', 'USA +1')], default='503', max_length=5),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
