# Generated by Django 6.0.1 on 2026-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0006_perfil_nombre_perfil_prefijo_alter_perfil_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('ALQUILER', 'Alquiler'), ('CAMBIO', 'Cambio / Permuta'), ('SERVICIO', 'Servicio')], max_length=10, null=True),
        ),
    ]
